In [5]:
import numpy as np

In [1]:
x = [1, 2, 3]
y = [4, 5, 10]

In [6]:
x = np.array(x)
y = np.array(y)

In [7]:
x

array([1, 2, 3])

In [8]:
y

array([ 4,  5, 10])

In [12]:
x / y

array([0.25, 0.4 , 0.3 ])

In [13]:
x + 1.1

array([2.1, 3.1, 4.1])

In [18]:
x = np.random.rand(10000)

In [23]:
x

array([0.32529511, 0.73474794, 0.42773188, ..., 0.44229561, 0.65023992,
       0.90476618])

In [24]:
x_list = list(x)

In [25]:
type(x)

numpy.ndarray

In [26]:
type(x_list)

list

In [27]:
x[0]

0.3252951090969898

In [28]:
x_list[0]

0.3252951090969898

In [33]:
speed_1 = %timeit -o sum(x_list)

1.39 ms ± 64.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
speed_2 = %timeit -o x.sum()

13 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
speed_1.average / speed_2.average

106.58142804245611

In [39]:
(x > 0.65).sum()

3501

In [41]:
speed_1 = %timeit -o sum([x_i > 0.65 for x_i in x_list])

55.4 ms ± 4.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
speed_2 = %timeit -o (x > 0.65).sum()

37.2 µs ± 724 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
speed_1.average / speed_2.average

1488.820500327192

In [44]:
x

array([0.32529511, 0.73474794, 0.42773188, ..., 0.44229561, 0.65023992,
       0.90476618])

In [45]:
x[0]

0.3252951090969898

In [46]:
x[100]

0.8326689878685428

In [47]:
x[111]

0.6729876888839729

In [54]:
x[::2]

array([0.32529511, 0.42773188, 0.78851244, ..., 0.08316603, 0.84523646,
       0.65023992])

In [67]:
x[::100]

array([0.32529511, 0.83266899, 0.65280853, ..., 0.77861924, 0.62811163,
       0.09318556])

In [122]:
x = np.random.rand(10,2,3)

In [76]:
x = np.random.uniform(size = (10, 5, 10))

In [92]:
np.full((10, 2), 3.14)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [102]:
x = np.ones(10, dtype=np.bool)

In [103]:
type(x)

numpy.ndarray

In [104]:
x.dtype

dtype('bool')

In [105]:
x

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [108]:
x

array([0.97058713, 0.97238236, 0.71387343, 0.48957487, 0.67576948,
       0.75362392, 0.47799818, 0.74990568, 0.4600405 , 0.05378973])

In [109]:
x.dtype = np.bool

In [110]:
x

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [111]:
x = 12.1

In [112]:
x

12.1

In [113]:
type(x)

float

In [114]:
int(x)

12

In [115]:
bool(x)

True

In [117]:
bool(0.0)

False

In [118]:
int([1, 2, 3])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [120]:
list(map(int, [1.1, 2.7, 3]))

[1, 2, 3]

In [147]:
x = np.random.rand(1000)

In [148]:
x

array([0.31389871, 0.61093937, 0.54290651, ..., 0.85487607, 0.56222347,
       0.78783648])

In [149]:
y = x[0:10]

In [152]:
x 

array([0.31389871, 0.61093937, 0.54290651, ..., 0.85487607, 0.56222347,
       0.78783648])

In [153]:
y

array([0.31389871, 0.61093937, 0.54290651, 0.57752962, 0.51228125,
       0.61604771, 0.18386913, 0.91203489, 0.10373117, 0.28896534])

In [154]:
x += 1

In [155]:
x

array([1.31389871, 1.61093937, 1.54290651, ..., 1.85487607, 1.56222347,
       1.78783648])

In [156]:
y

array([1.31389871, 1.61093937, 1.54290651, 1.57752962, 1.51228125,
       1.61604771, 1.18386913, 1.91203489, 1.10373117, 1.28896534])

In [157]:
x = np.random.rand(10, 3)

In [158]:
x

array([[0.81667594, 0.08637487, 0.68117205],
       [0.67363437, 0.0321019 , 0.73234833],
       [0.24124734, 0.59545111, 0.71145552],
       [0.86074075, 0.24288785, 0.57027877],
       [0.35116858, 0.3612141 , 0.58239069],
       [0.80036997, 0.45240958, 0.11631252],
       [0.44767018, 0.02069714, 0.98825204],
       [0.13763143, 0.46596305, 0.15029576],
       [0.57483415, 0.1126058 , 0.45731206],
       [0.76022998, 0.75804305, 0.39966317]])

In [159]:
x.sum()

14.181432063585369

In [160]:
x.sum(axis = 0)

array([5.66420269, 3.12774847, 5.3894809 ])

In [161]:
x.sum(axis = 1)

array([1.58422287, 1.4380846 , 1.54815397, 1.67390736, 1.29477337,
       1.36909207, 1.45661936, 0.75389025, 1.14475202, 1.91793619])

In [162]:
x = np.random.rand(10, 3, 5)

In [163]:
x.sum(axis = 2)

array([[1.8272487 , 2.14130565, 2.93311241],
       [3.10495761, 1.00220737, 1.53912375],
       [1.18213134, 1.98107236, 2.86430378],
       [2.86330554, 1.24226016, 2.56768979],
       [2.41849284, 2.41994739, 1.21964521],
       [3.04451682, 2.14382607, 3.3691311 ],
       [3.20679916, 2.74255416, 2.71809573],
       [3.00230855, 3.03015861, 2.91740005],
       [2.20701745, 2.79781557, 2.89757007],
       [2.97448413, 1.92515645, 3.46150133]])

In [164]:
x = np.random.rand(10, 3)

In [168]:
x

array([[0.82602649, 0.45579101, 0.05334771],
       [0.45355714, 0.22410523, 0.54396782],
       [0.37202394, 0.09656626, 0.87822392],
       [0.54520867, 0.13017213, 0.8954115 ],
       [0.31376946, 0.7462505 , 0.80362045],
       [0.02768311, 0.22676542, 0.21394625],
       [0.55970854, 0.63376936, 0.05688279],
       [0.00851934, 0.85930592, 0.76058409],
       [0.14554917, 0.181052  , 0.73669857],
       [0.78507242, 0.40953137, 0.24327413]])

In [171]:
x.cumsum(axis=1)

array([[0.82602649, 1.2818175 , 1.33516521],
       [0.45355714, 0.67766236, 1.22163018],
       [0.37202394, 0.4685902 , 1.34681412],
       [0.54520867, 0.6753808 , 1.57079231],
       [0.31376946, 1.06001995, 1.8636404 ],
       [0.02768311, 0.25444853, 0.46839478],
       [0.55970854, 1.1934779 , 1.2503607 ],
       [0.00851934, 0.86782527, 1.62840936],
       [0.14554917, 0.32660117, 1.06329974],
       [0.78507242, 1.19460379, 1.43787792]])

In [174]:
x.max(axis=1)

array([0.82602649, 0.54396782, 0.87822392, 0.8954115 , 0.80362045,
       0.22676542, 0.63376936, 0.85930592, 0.73669857, 0.78507242])

In [176]:
x

array([[0.82602649, 0.45579101, 0.05334771],
       [0.45355714, 0.22410523, 0.54396782],
       [0.37202394, 0.09656626, 0.87822392],
       [0.54520867, 0.13017213, 0.8954115 ],
       [0.31376946, 0.7462505 , 0.80362045],
       [0.02768311, 0.22676542, 0.21394625],
       [0.55970854, 0.63376936, 0.05688279],
       [0.00851934, 0.85930592, 0.76058409],
       [0.14554917, 0.181052  , 0.73669857],
       [0.78507242, 0.40953137, 0.24327413]])

In [175]:
x.argmax(axis=0)

array([0, 7, 3])

In [177]:
x.max(axis = 0)

array([0.82602649, 0.85930592, 0.8954115 ])

In [178]:
x.argmin(axis=0)

array([7, 2, 0])

In [179]:
x.sort(axis =0)

In [180]:
x

array([[0.00851934, 0.09656626, 0.05334771],
       [0.02768311, 0.13017213, 0.05688279],
       [0.14554917, 0.181052  , 0.21394625],
       [0.31376946, 0.22410523, 0.24327413],
       [0.37202394, 0.22676542, 0.54396782],
       [0.45355714, 0.40953137, 0.73669857],
       [0.54520867, 0.45579101, 0.76058409],
       [0.55970854, 0.63376936, 0.80362045],
       [0.78507242, 0.7462505 , 0.87822392],
       [0.82602649, 0.85930592, 0.8954115 ]])

In [181]:
x

array([[0.00851934, 0.09656626, 0.05334771],
       [0.02768311, 0.13017213, 0.05688279],
       [0.14554917, 0.181052  , 0.21394625],
       [0.31376946, 0.22410523, 0.24327413],
       [0.37202394, 0.22676542, 0.54396782],
       [0.45355714, 0.40953137, 0.73669857],
       [0.54520867, 0.45579101, 0.76058409],
       [0.55970854, 0.63376936, 0.80362045],
       [0.78507242, 0.7462505 , 0.87822392],
       [0.82602649, 0.85930592, 0.8954115 ]])

In [182]:
x.sum(axis =0)

array([4.03711828, 3.9633092 , 5.18595724])

In [184]:
x.median(axis = 0)

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [185]:
np.median(x, axis=0)

array([0.41279054, 0.31814839, 0.64033319])

In [186]:
x.mean(axis = 0)

array([0.40371183, 0.39633092, 0.51859572])

In [188]:
x = np.random.rand(10, 3)

In [189]:
y = np.random.rand(5, 3)

In [190]:
x


array([[0.69637111, 0.66444139, 0.38339166],
       [0.64242896, 0.21725823, 0.32317457],
       [0.07299015, 0.6468958 , 0.71912861],
       [0.49397987, 0.80529549, 0.73453339],
       [0.72991917, 0.77567316, 0.10259317],
       [0.16851091, 0.31231271, 0.93255034],
       [0.22073245, 0.19707639, 0.86810839],
       [0.84257633, 0.03441338, 0.9326556 ],
       [0.89014712, 0.35810623, 0.10195867],
       [0.58978152, 0.16945091, 0.65050642]])

In [191]:
y

array([[0.2385312 , 0.46315562, 0.32632409],
       [0.58018636, 0.07431591, 0.64784793],
       [0.41227299, 0.09546046, 0.72494011],
       [0.44304115, 0.83274299, 0.29147078],
       [0.56019584, 0.11585983, 0.53018199]])

In [192]:
np.vstack((x, y))

array([[0.69637111, 0.66444139, 0.38339166],
       [0.64242896, 0.21725823, 0.32317457],
       [0.07299015, 0.6468958 , 0.71912861],
       [0.49397987, 0.80529549, 0.73453339],
       [0.72991917, 0.77567316, 0.10259317],
       [0.16851091, 0.31231271, 0.93255034],
       [0.22073245, 0.19707639, 0.86810839],
       [0.84257633, 0.03441338, 0.9326556 ],
       [0.89014712, 0.35810623, 0.10195867],
       [0.58978152, 0.16945091, 0.65050642],
       [0.2385312 , 0.46315562, 0.32632409],
       [0.58018636, 0.07431591, 0.64784793],
       [0.41227299, 0.09546046, 0.72494011],
       [0.44304115, 0.83274299, 0.29147078],
       [0.56019584, 0.11585983, 0.53018199]])

In [193]:
np.r_[x,y]

array([[0.69637111, 0.66444139, 0.38339166],
       [0.64242896, 0.21725823, 0.32317457],
       [0.07299015, 0.6468958 , 0.71912861],
       [0.49397987, 0.80529549, 0.73453339],
       [0.72991917, 0.77567316, 0.10259317],
       [0.16851091, 0.31231271, 0.93255034],
       [0.22073245, 0.19707639, 0.86810839],
       [0.84257633, 0.03441338, 0.9326556 ],
       [0.89014712, 0.35810623, 0.10195867],
       [0.58978152, 0.16945091, 0.65050642],
       [0.2385312 , 0.46315562, 0.32632409],
       [0.58018636, 0.07431591, 0.64784793],
       [0.41227299, 0.09546046, 0.72494011],
       [0.44304115, 0.83274299, 0.29147078],
       [0.56019584, 0.11585983, 0.53018199]])

In [194]:
z = numpy.random.rand(100)

In [195]:
#(x >0.65).sum() 

In [198]:
np.sum(z > 0.65)

39

In [200]:
(z > 0.65).sum()

In [201]:
w = z > 0.65
w.sum()

39

In [202]:
range(10)

range(0, 10)

In [203]:
x

array([[0.69637111, 0.66444139, 0.38339166],
       [0.64242896, 0.21725823, 0.32317457],
       [0.07299015, 0.6468958 , 0.71912861],
       [0.49397987, 0.80529549, 0.73453339],
       [0.72991917, 0.77567316, 0.10259317],
       [0.16851091, 0.31231271, 0.93255034],
       [0.22073245, 0.19707639, 0.86810839],
       [0.84257633, 0.03441338, 0.9326556 ],
       [0.89014712, 0.35810623, 0.10195867],
       [0.58978152, 0.16945091, 0.65050642]])

In [207]:
y = np.random.rand(10, 2)

In [208]:
np.hstack((x,y))

array([[0.69637111, 0.66444139, 0.38339166, 0.08139946, 0.12966981],
       [0.64242896, 0.21725823, 0.32317457, 0.73967624, 0.4559757 ],
       [0.07299015, 0.6468958 , 0.71912861, 0.76797124, 0.91632375],
       [0.49397987, 0.80529549, 0.73453339, 0.87107929, 0.30022665],
       [0.72991917, 0.77567316, 0.10259317, 0.77085968, 0.02373335],
       [0.16851091, 0.31231271, 0.93255034, 0.73711951, 0.53167683],
       [0.22073245, 0.19707639, 0.86810839, 0.04270184, 0.15356904],
       [0.84257633, 0.03441338, 0.9326556 , 0.42164892, 0.25721444],
       [0.89014712, 0.35810623, 0.10195867, 0.64234732, 0.34947892],
       [0.58978152, 0.16945091, 0.65050642, 0.06538608, 0.84766146]])

In [209]:
x, y


(array([[0.69637111, 0.66444139, 0.38339166],
        [0.64242896, 0.21725823, 0.32317457],
        [0.07299015, 0.6468958 , 0.71912861],
        [0.49397987, 0.80529549, 0.73453339],
        [0.72991917, 0.77567316, 0.10259317],
        [0.16851091, 0.31231271, 0.93255034],
        [0.22073245, 0.19707639, 0.86810839],
        [0.84257633, 0.03441338, 0.9326556 ],
        [0.89014712, 0.35810623, 0.10195867],
        [0.58978152, 0.16945091, 0.65050642]]),
 array([[0.08139946, 0.12966981],
        [0.73967624, 0.4559757 ],
        [0.76797124, 0.91632375],
        [0.87107929, 0.30022665],
        [0.77085968, 0.02373335],
        [0.73711951, 0.53167683],
        [0.04270184, 0.15356904],
        [0.42164892, 0.25721444],
        [0.64234732, 0.34947892],
        [0.06538608, 0.84766146]]))

In [210]:
np.c_[x,y]

array([[0.69637111, 0.66444139, 0.38339166, 0.08139946, 0.12966981],
       [0.64242896, 0.21725823, 0.32317457, 0.73967624, 0.4559757 ],
       [0.07299015, 0.6468958 , 0.71912861, 0.76797124, 0.91632375],
       [0.49397987, 0.80529549, 0.73453339, 0.87107929, 0.30022665],
       [0.72991917, 0.77567316, 0.10259317, 0.77085968, 0.02373335],
       [0.16851091, 0.31231271, 0.93255034, 0.73711951, 0.53167683],
       [0.22073245, 0.19707639, 0.86810839, 0.04270184, 0.15356904],
       [0.84257633, 0.03441338, 0.9326556 , 0.42164892, 0.25721444],
       [0.89014712, 0.35810623, 0.10195867, 0.64234732, 0.34947892],
       [0.58978152, 0.16945091, 0.65050642, 0.06538608, 0.84766146]])

# Broadcasting

In [211]:
x = np.random.rand(5)

In [212]:
x

array([0.65045838, 0.53752055, 0.34434807, 0.25223743, 0.99242595])

In [213]:
x + 1.0

array([1.65045838, 1.53752055, 1.34434807, 1.25223743, 1.99242595])

In [214]:
x

array([0.65045838, 0.53752055, 0.34434807, 0.25223743, 0.99242595])

In [215]:
y = np.random.rand(10, 5)

In [216]:
y


array([[0.09631779, 0.53349803, 0.56847575, 0.61809779, 0.53924942],
       [0.52880531, 0.74521263, 0.61306057, 0.29518349, 0.98267792],
       [0.75977914, 0.92025028, 0.63363018, 0.10041124, 0.51597239],
       [0.49174354, 0.93176643, 0.38028942, 0.45096997, 0.12897319],
       [0.52649174, 0.10733483, 0.80241957, 0.43833684, 0.70878441],
       [0.30804038, 0.23345075, 0.60986876, 0.42534606, 0.99900952],
       [0.5917852 , 0.39511589, 0.84817708, 0.5527792 , 0.60109119],
       [0.38342105, 0.37001242, 0.93381579, 0.24720767, 0.00621821],
       [0.80954809, 0.40098908, 0.5916726 , 0.50066323, 0.08140898],
       [0.40781232, 0.59625077, 0.69632097, 0.07552305, 0.53585908]])

In [217]:
x

array([0.65045838, 0.53752055, 0.34434807, 0.25223743, 0.99242595])

In [218]:
x + y

array([[0.74677617, 1.07101858, 0.91282382, 0.87033522, 1.53167536],
       [1.17926369, 1.28273318, 0.95740864, 0.54742092, 1.97510387],
       [1.41023752, 1.45777083, 0.97797825, 0.35264867, 1.50839834],
       [1.14220192, 1.46928697, 0.72463749, 0.7032074 , 1.12139914],
       [1.17695012, 0.64485537, 1.14676764, 0.69057427, 1.70121036],
       [0.95849876, 0.7709713 , 0.95421683, 0.67758349, 1.99143547],
       [1.24224358, 0.93263644, 1.19252515, 0.80501663, 1.59351714],
       [1.03387943, 0.90753296, 1.27816386, 0.49944509, 0.99864416],
       [1.46000647, 0.93850962, 0.93602067, 0.75290066, 1.07383492],
       [1.0582707 , 1.13377132, 1.04066904, 0.32776048, 1.52828502]])

In [220]:
y.shape

(10, 5)

In [223]:
y[0]

array([0.09631779, 0.53349803, 0.56847575, 0.61809779, 0.53924942])

In [224]:
x 

array([0.65045838, 0.53752055, 0.34434807, 0.25223743, 0.99242595])

In [225]:
y[0]

array([0.09631779, 0.53349803, 0.56847575, 0.61809779, 0.53924942])

In [228]:
x + y[1]

array([1.17926369, 1.28273318, 0.95740864, 0.54742092, 1.97510387])

In [227]:
x + y

array([[0.74677617, 1.07101858, 0.91282382, 0.87033522, 1.53167536],
       [1.17926369, 1.28273318, 0.95740864, 0.54742092, 1.97510387],
       [1.41023752, 1.45777083, 0.97797825, 0.35264867, 1.50839834],
       [1.14220192, 1.46928697, 0.72463749, 0.7032074 , 1.12139914],
       [1.17695012, 0.64485537, 1.14676764, 0.69057427, 1.70121036],
       [0.95849876, 0.7709713 , 0.95421683, 0.67758349, 1.99143547],
       [1.24224358, 0.93263644, 1.19252515, 0.80501663, 1.59351714],
       [1.03387943, 0.90753296, 1.27816386, 0.49944509, 0.99864416],
       [1.46000647, 0.93850962, 0.93602067, 0.75290066, 1.07383492],
       [1.0582707 , 1.13377132, 1.04066904, 0.32776048, 1.52828502]])

In [231]:
y.shape

(10, 5)

In [232]:
y

array([[0.09631779, 0.53349803, 0.56847575, 0.61809779, 0.53924942],
       [0.52880531, 0.74521263, 0.61306057, 0.29518349, 0.98267792],
       [0.75977914, 0.92025028, 0.63363018, 0.10041124, 0.51597239],
       [0.49174354, 0.93176643, 0.38028942, 0.45096997, 0.12897319],
       [0.52649174, 0.10733483, 0.80241957, 0.43833684, 0.70878441],
       [0.30804038, 0.23345075, 0.60986876, 0.42534606, 0.99900952],
       [0.5917852 , 0.39511589, 0.84817708, 0.5527792 , 0.60109119],
       [0.38342105, 0.37001242, 0.93381579, 0.24720767, 0.00621821],
       [0.80954809, 0.40098908, 0.5916726 , 0.50066323, 0.08140898],
       [0.40781232, 0.59625077, 0.69632097, 0.07552305, 0.53585908]])

In [233]:
y.T

array([[0.09631779, 0.52880531, 0.75977914, 0.49174354, 0.52649174,
        0.30804038, 0.5917852 , 0.38342105, 0.80954809, 0.40781232],
       [0.53349803, 0.74521263, 0.92025028, 0.93176643, 0.10733483,
        0.23345075, 0.39511589, 0.37001242, 0.40098908, 0.59625077],
       [0.56847575, 0.61306057, 0.63363018, 0.38028942, 0.80241957,
        0.60986876, 0.84817708, 0.93381579, 0.5916726 , 0.69632097],
       [0.61809779, 0.29518349, 0.10041124, 0.45096997, 0.43833684,
        0.42534606, 0.5527792 , 0.24720767, 0.50066323, 0.07552305],
       [0.53924942, 0.98267792, 0.51597239, 0.12897319, 0.70878441,
        0.99900952, 0.60109119, 0.00621821, 0.08140898, 0.53585908]])

In [235]:
x = np.random.rand(10)

In [236]:
x

array([0.53821546, 0.01549303, 0.02248694, 0.42742327, 0.11334525,
       0.15115613, 0.15077264, 0.82802895, 0.48472666, 0.83565149])

In [239]:
x = np.random.rand(10, 3)

In [240]:
y = np.random.rand(3, 2)

In [241]:
x

array([[0.04280709, 0.09753745, 0.15150553],
       [0.00268942, 0.76252082, 0.46443389],
       [0.01517137, 0.26818047, 0.73264641],
       [0.62231373, 0.49394515, 0.13737445],
       [0.33236687, 0.99999566, 0.10164843],
       [0.15444439, 0.64072023, 0.21617835],
       [0.01384968, 0.08114244, 0.83729285],
       [0.1477511 , 0.78085261, 0.66688795],
       [0.93193839, 0.90620243, 0.68865022],
       [0.40160595, 0.76100333, 0.00885691]])

In [242]:
y

array([[0.73296556, 0.28696092],
       [0.51710614, 0.89951326],
       [0.56968514, 0.47588415]])

In [244]:
np.dot(x, y)

array([[0.16812379, 0.17211927],
       [0.66085654, 0.90768608],
       [0.56717564, 0.59424029],
       [0.78981678, 0.68826426],
       [0.81862496, 1.04325853],
       [0.56767638, 0.7235317 ],
       [0.52910389, 0.47541742],
       [0.8919963 , 1.06214747],
       [1.54399538, 1.41028873],
       [0.69292848, 0.80399267]])

In [245]:
x @ y 

array([[0.16812379, 0.17211927],
       [0.66085654, 0.90768608],
       [0.56717564, 0.59424029],
       [0.78981678, 0.68826426],
       [0.81862496, 1.04325853],
       [0.56767638, 0.7235317 ],
       [0.52910389, 0.47541742],
       [0.8919963 , 1.06214747],
       [1.54399538, 1.41028873],
       [0.69292848, 0.80399267]])

In [246]:
np.inner(x, y.T)

array([[0.16812379, 0.17211927],
       [0.66085654, 0.90768608],
       [0.56717564, 0.59424029],
       [0.78981678, 0.68826426],
       [0.81862496, 1.04325853],
       [0.56767638, 0.7235317 ],
       [0.52910389, 0.47541742],
       [0.8919963 , 1.06214747],
       [1.54399538, 1.41028873],
       [0.69292848, 0.80399267]])

# K nearest neighbours

In [249]:
x = np.random.rand(10000, 3)

In [250]:
x

array([[0.17852938, 0.10043705, 0.49148034],
       [0.31571556, 0.83154293, 0.82944347],
       [0.58023556, 0.82902078, 0.51087023],
       ...,
       [0.63084147, 0.1637215 , 0.04961797],
       [0.55996257, 0.69944043, 0.5306189 ],
       [0.06378925, 0.09187908, 0.68856575]])

In [251]:
centroids = np.random.rand(5, 3)

In [252]:
centroids

array([[0.14148061, 0.56443537, 0.23246364],
       [0.5387532 , 0.50983247, 0.57717325],
       [0.98929648, 0.70372927, 0.71904536],
       [0.45639578, 0.28576296, 0.43380822],
       [0.63926379, 0.19007637, 0.93749095]])

In [253]:
x[0]

array([0.17852938, 0.10043705, 0.49148034])

In [254]:
centroids[0]

array([0.14148061, 0.56443537, 0.23246364])

In [259]:
np.sqrt(((x[0] - centroids[0])**2).sum())

0.5326881914861603

In [261]:
def euclidean(x, y):
    return np.sqrt(np.sum((x - y)**2))

In [262]:
euclidean(x[0], centroids[0])

0.5326881914861603

In [275]:
%%timeit 

n = 10000
K = 5

distances = np.empty((n,K))

for i in range(n):
    for k in range(K):
        distances[i, k] = euclidean(x[i], centroids[k])

1.25 s ± 68.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [276]:
x.shape



(10000, 3)

In [277]:
centroids.shape

(5, 3)

In [282]:
x.reshape((n,1,3)) 

array([[[0.17852938, 0.10043705, 0.49148034]],

       [[0.31571556, 0.83154293, 0.82944347]],

       [[0.58023556, 0.82902078, 0.51087023]],

       ...,

       [[0.63084147, 0.1637215 , 0.04961797]],

       [[0.55996257, 0.69944043, 0.5306189 ]],

       [[0.06378925, 0.09187908, 0.68856575]]])

In [284]:
x.reshape((n, 1, 3)).shape

(10000, 1, 3)

In [285]:
centroids.shape

(5, 3)

In [286]:
w = np.array([1.0, 2.0, 3.0])




In [289]:
w - centroids

array([[0.85851939, 1.43556463, 2.76753636],
       [0.4612468 , 1.49016753, 2.42282675],
       [0.01070352, 1.29627073, 2.28095464],
       [0.54360422, 1.71423704, 2.56619178],
       [0.36073621, 1.80992363, 2.06250905]])

In [290]:
w

array([1., 2., 3.])

In [305]:
%%timeit 

distances2 = np.sqrt(np.sum((x.reshape((n, 1, 3)) - centroids)**2, axis=2))


2.5 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [300]:
distances.shape

(10000, 5)

In [304]:
(distances2 == distances).all()

True

In [306]:
1250/2.5


500.0