In [13]:
import pandas as pd
import numpy as np

In [2]:
affairs_df = pd.read_csv('affairs.csv')

In [3]:
affairs_df

affairs  gender   age  yearsmarried children  religiousness  education  \
0          0    male  37.0         10.00       no              3         18   
1          0  female  27.0          4.00       no              4         14   
2          0  female  32.0         15.00      yes              1         12   
3          0    male  57.0         15.00      yes              5         18   
4          0    male  22.0          0.75       no              2         17   
..       ...     ...   ...           ...      ...            ...        ...   
596        1    male  22.0          1.50      yes              1         12   
597        7  female  32.0         10.00      yes              2         18   
598        2    male  32.0         10.00      yes              2         17   
599        2    male  22.0          7.00      yes              3         18   
600        1  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 9 columns]

## select

A `select` is where we select the columns.

In [4]:
affairs_df[['affairs', 'gender', 'gender']]

affairs  gender  gender
0          0    male    male
1          0  female  female
2          0  female  female
3          0    male    male
4          0    male    male
..       ...     ...     ...
596        1    male    male
597        7  female  female
598        2    male    male
599        2    male    male
600        1  female  female

[601 rows x 3 columns]

In [5]:
affairs_df.drop(columns = ['affairs', 'age'])

gender  yearsmarried children  religiousness  education  occupation  \
0      male         10.00       no              3         18           7   
1    female          4.00       no              4         14           6   
2    female         15.00      yes              1         12           1   
3      male         15.00      yes              5         18           6   
4      male          0.75       no              2         17           6   
..      ...           ...      ...            ...        ...         ...   
596    male          1.50      yes              1         12           2   
597  female         10.00      yes              2         18           5   
598    male         10.00      yes              2         17           6   
599    male          7.00      yes              3         18           6   
600  female         15.00      yes              3         14           1   

     rating  
0         4  
1         4  
2         4  
3         5  
4         3  
..      ...  
596       5  
597       4  
598       5  
599       2  
600       5  

[601 rows x 7 columns]

In [8]:
affairs_df.filter(regex = '^a')

affairs   age
0          0  37.0
1          0  27.0
2          0  32.0
3          0  57.0
4          0  22.0
..       ...   ...
596        1  22.0
597        7  32.0
598        2  32.0
599        2  22.0
600        1  32.0

[601 rows x 2 columns]

In [12]:
affairs_df.iloc[:, [0, 1, 4]]

affairs  gender children
0          0    male       no
1          0  female       no
2          0  female      yes
3          0    male      yes
4          0    male       no
..       ...     ...      ...
596        1    male      yes
597        7  female      yes
598        2    male      yes
599        2    male      yes
600        1  female      yes

[601 rows x 3 columns]

In [14]:
x = np.random.rand(5, 3)

In [17]:
x[:,[0,2]]

array([[0.31751184, 0.74070994],
       [0.92307994, 0.47082289],
       [0.21992044, 0.87808879],
       [0.24175678, 0.5504743 ],
       [0.81408735, 0.5830389 ]])

In [19]:
affairs_df.loc[:,['affairs','age']]

affairs   age
0          0  37.0
1          0  27.0
2          0  32.0
3          0  57.0
4          0  22.0
..       ...   ...
596        1  22.0
597        7  32.0
598        2  32.0
599        2  22.0
600        1  32.0

[601 rows x 2 columns]

In [20]:
affairs_df

affairs  gender   age  yearsmarried children  religiousness  education  \
0          0    male  37.0         10.00       no              3         18   
1          0  female  27.0          4.00       no              4         14   
2          0  female  32.0         15.00      yes              1         12   
3          0    male  57.0         15.00      yes              5         18   
4          0    male  22.0          0.75       no              2         17   
..       ...     ...   ...           ...      ...            ...        ...   
596        1    male  22.0          1.50      yes              1         12   
597        7  female  32.0         10.00      yes              2         18   
598        2    male  32.0         10.00      yes              2         17   
599        2    male  22.0          7.00      yes              3         18   
600        1  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 9 columns]

In [21]:
affairs_df.loc[:, 'gender':'religiousness']

gender   age  yearsmarried children  religiousness
0      male  37.0         10.00       no              3
1    female  27.0          4.00       no              4
2    female  32.0         15.00      yes              1
3      male  57.0         15.00      yes              5
4      male  22.0          0.75       no              2
..      ...   ...           ...      ...            ...
596    male  22.0          1.50      yes              1
597  female  32.0         10.00      yes              2
598    male  32.0         10.00      yes              2
599    male  22.0          7.00      yes              3
600  female  32.0         15.00      yes              3

[601 rows x 5 columns]

In [22]:
affairs_df.iloc[3:10, 0:3]

affairs  gender   age
3        0    male  57.0
4        0    male  22.0
5        0  female  32.0
6        0  female  22.0
7        0    male  57.0
8        0  female  32.0
9        0    male  22.0

In [30]:
affairs_df.age > 25

0       True
1       True
2       True
3       True
4      False
       ...  
596    False
597     True
598     True
599    False
600     True
Name: age, Length: 601, dtype: bool

In [33]:
affairs_df.loc[affairs_df.age <= 20, ['children', 'rating']]

children  rating
80       yes       5
305       no       4
419       no       5
482       no       5
540      yes       3
571      yes       5

## filtering

What I am calling `filtering` is where we select rows by values of variables.

In [34]:
affairs_df[affairs_df.gender == 'male']

affairs gender   age  yearsmarried children  religiousness  education  \
0          0   male  37.0         10.00       no              3         18   
3          0   male  57.0         15.00      yes              5         18   
4          0   male  22.0          0.75       no              2         17   
7          0   male  57.0         15.00      yes              2         14   
9          0   male  22.0          1.50       no              4         14   
..       ...    ...   ...           ...      ...            ...        ...   
594        3   male  32.0         10.00      yes              4         14   
595        7   male  47.0         15.00      yes              3         16   
596        1   male  22.0          1.50      yes              1         12   
598        2   male  32.0         10.00      yes              2         17   
599        2   male  22.0          7.00      yes              3         18   

     occupation  rating  
0             7       4  
3             6       5  
4             6       3  
7             4       4  
9             4       5  
..          ...     ...  
594           4       3  
595           4       2  
596           2       5  
598           6       5  
599           6       2  

[286 rows x 9 columns]

In [37]:
x = affairs_df.gender == 'male'

In [41]:
x.values.dtype

dtype('bool')

In [43]:
x = np.array([True, True, False])
y = np.array([False, True, False])

In [44]:
x

array([ True,  True, False])

In [45]:
y


array([False,  True, False])

In [47]:
x & y

array([False,  True, False])

In [48]:
x


array([ True,  True, False])

In [49]:
y

array([False,  True, False])

In [50]:
x and y 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [51]:
x & y

array([False,  True, False])

In [52]:
True and False 

False

In [55]:
affairs_df[(affairs_df.gender == 'male') & 
           (affairs_df.children == 'yes')]

affairs gender   age  yearsmarried children  religiousness  education  \
3          0   male  57.0          15.0      yes              5         18   
7          0   male  57.0          15.0      yes              2         14   
10         0   male  37.0          15.0      yes              2         20   
11         0   male  27.0           4.0      yes              4         18   
12         0   male  47.0          15.0      yes              5         17   
..       ...    ...   ...           ...      ...            ...        ...   
594        3   male  32.0          10.0      yes              4         14   
595        7   male  47.0          15.0      yes              3         16   
596        1   male  22.0           1.5      yes              1         12   
598        2   male  32.0          10.0      yes              2         17   
599        2   male  22.0           7.0      yes              3         18   

     occupation  rating  
3             6       5  
7             4       4  
10            7       2  
11            6       4  
12            6       4  
..          ...     ...  
594           4       3  
595           4       2  
596           2       5  
598           6       5  
599           6       2  

[214 rows x 9 columns]

In [56]:
x = np.random.rand(10)

In [57]:
x

array([0.25780436, 0.17436974, 0.66772378, 0.39303331, 0.31742378,
       0.28118268, 0.41830285, 0.48025269, 0.33987605, 0.19626713])

In [59]:
x[x < 0.2]

array([0.17436974, 0.19626713])

In [62]:
affairs_df[(affairs_df.gender == 'male') & 
           (affairs_df.children == 'yes')]

affairs gender   age  yearsmarried children  religiousness  education  \
3          0   male  57.0          15.0      yes              5         18   
7          0   male  57.0          15.0      yes              2         14   
10         0   male  37.0          15.0      yes              2         20   
11         0   male  27.0           4.0      yes              4         18   
12         0   male  47.0          15.0      yes              5         17   
..       ...    ...   ...           ...      ...            ...        ...   
594        3   male  32.0          10.0      yes              4         14   
595        7   male  47.0          15.0      yes              3         16   
596        1   male  22.0           1.5      yes              1         12   
598        2   male  32.0          10.0      yes              2         17   
599        2   male  22.0           7.0      yes              3         18   

     occupation  rating  
3             6       5  
7             4       4  
10            7       2  
11            6       4  
12            6       4  
..          ...     ...  
594           4       3  
595           4       2  
596           2       5  
598           6       5  
599           6       2  

[214 rows x 9 columns]

In [61]:
affairs_df.query('gender == "male" & children == "yes"')

affairs gender   age  yearsmarried children  religiousness  education  \
3          0   male  57.0          15.0      yes              5         18   
7          0   male  57.0          15.0      yes              2         14   
10         0   male  37.0          15.0      yes              2         20   
11         0   male  27.0           4.0      yes              4         18   
12         0   male  47.0          15.0      yes              5         17   
..       ...    ...   ...           ...      ...            ...        ...   
594        3   male  32.0          10.0      yes              4         14   
595        7   male  47.0          15.0      yes              3         16   
596        1   male  22.0           1.5      yes              1         12   
598        2   male  32.0          10.0      yes              2         17   
599        2   male  22.0           7.0      yes              3         18   

     occupation  rating  
3             6       5  
7             4       4  
10            7       2  
11            6       4  
12            6       4  
..          ...     ...  
594           4       3  
595           4       2  
596           2       5  
598           6       5  
599           6       2  

[214 rows x 9 columns]

In [63]:
%rep 61

In [65]:
affairs_df.query('gender == "male" & children == "yes"').loc[:,['affairs',
                                                                'age']]

affairs   age
3          0  57.0
7          0  57.0
10         0  37.0
11         0  27.0
12         0  47.0
..       ...   ...
594        3  32.0
595        7  47.0
596        1  22.0
598        2  32.0
599        2  22.0

[214 rows x 2 columns]

## sampling

In [69]:
affairs_df.sample(n = 10)

affairs  gender   age  yearsmarried children  religiousness  education  \
579        1    male  42.0          15.0      yes              3         16   
16         0  female  37.0          15.0      yes              2         18   
319        0    male  52.0          15.0      yes              4         12   
594        3    male  32.0          10.0      yes              4         14   
413        0    male  42.0          10.0      yes              4         18   
277        0  female  37.0          15.0      yes              2         17   
432        0    male  27.0           4.0      yes              4         17   
597        7  female  32.0          10.0      yes              2         18   
592        7  female  42.0          15.0      yes              2         14   
569        7  female  37.0          15.0      yes              2         17   

     occupation  rating  
579           6       3  
16            4       3  
319           2       4  
594           4       3  
413           6       4  
277           5       5  
432           4       4  
597           5       4  
592           3       2  
569           6       4

In [70]:
affairs_df.sample(frac = 0.1)

affairs  gender   age  yearsmarried children  religiousness  education  \
373        0  female  27.0         1.500       no              4         17   
49         0    male  42.0        15.000      yes              2         20   
239        0  female  37.0        15.000      yes              4         16   
298        0    male  37.0        15.000      yes              4         18   
320        0  female  22.0         0.417       no              3         17   
307        0  female  32.0         0.750       no              5         14   
350        0  female  27.0         1.500       no              2         16   
394        0  female  32.0         7.000      yes              2         14   
454       12  female  32.0        10.000      yes              3         17   
152        0    male  32.0         4.000      yes              2         18   
420        0    male  22.0         4.000      yes              4         16   
466        3    male  27.0         4.000       no              1         18   
228        0    male  37.0        15.000      yes              4         14   
584        3    male  32.0         4.000      yes              3         20   
528        1  female  32.0         7.000      yes              3         17   
72         0  female  22.0         0.125       no              2         12   
436        0  female  42.0        15.000      yes              2         14   
408        0  female  27.0         7.000       no              2         17   
297        0  female  27.0         4.000       no              2         18   
11         0    male  27.0         4.000      yes              4         18   
207        0  female  22.0         1.500       no              1         14   
278        0    male  47.0        15.000       no              4         20   
355        0  female  47.0        15.000      yes              2         14   
500        3    male  47.0        15.000      yes              5         16   
359        0    male  27.0         0.125       no              3         20   
189        0    male  32.0        15.000      yes              1         14   
190        0    male  22.0         0.750       no              3         17   
459        2    male  37.0        15.000      yes              2         18   
188        0    male  32.0        10.000      yes              4         16   
563       12    male  37.0        15.000      yes              2         17   
4          0    male  22.0         0.750       no              2         17   
564       12  female  27.0         4.000       no              2         14   
322        0    male  27.0         4.000      yes              4         20   
578       12    male  37.0        15.000       no              3         14   
201        0    male  32.0         4.000      yes              2         14   
535        1    male  27.0        10.000      yes              5         20   
289        0  female  37.0        15.000      yes              2         18   
372        0    male  32.0         7.000      yes              2         18   
546       12  female  32.0        15.000       no              3         17   
33         0  female  42.0        15.000      yes              5         14   
494        1    male  27.0         4.000      yes              3         18   
230        0  female  37.0        15.000      yes              5         14   
57         0  female  37.0        15.000      yes              4         17   
90         0  female  32.0        15.000      yes              4         14   
585        2    male  32.0        15.000      yes              5         20   
48         0    male  27.0         1.500      yes              4         16   
150        0    male  37.0         7.000      yes              4         20   
520        1  female  52.0        15.000      yes              3         14   
161        0  female  27.0         4.000      yes              2         18   
115        0    male  37.0        15.000       no      

In [71]:
affairs_df.nsmallest(10, 'age')

affairs  gender   age  yearsmarried children  religiousness  education  \
80         0    male  17.5          1.50      yes              3         18   
305        0  female  17.5          0.75       no              2         18   
419        0  female  17.5         10.00       no              4         14   
482        1  female  17.5          0.75       no              5         14   
540       12  female  17.5          0.75      yes              2         12   
571       12  female  17.5          0.75      yes              2         12   
4          0    male  22.0          0.75       no              2         17   
6          0  female  22.0          0.75       no              2         12   
9          0    male  22.0          1.50       no              4         14   
13         0  female  22.0          1.50       no              2         17   

     occupation  rating  
80            6       5  
305           5       4  
419           4       5  
482           4       5  
540           1       3  
571           3       5  
4             6       3  
6             1       3  
9             4       5  
13            5       4

In [72]:
affairs_df.nlargest(5, 'affairs')

affairs  gender   age  yearsmarried children  religiousness  education  \
454       12  female  32.0          10.0      yes              3         17   
457       12    male  37.0          15.0      yes              4         14   
463       12  female  42.0          15.0      yes              5          9   
464       12    male  37.0          10.0      yes              2         20   
465       12  female  32.0          15.0      yes              3         14   

     occupation  rating  
454           5       2  
457           5       2  
463           4       1  
464           6       2  
465           1       2

In [79]:
affairs_df[np.arange(len(affairs_df)) % 3 == 0]

affairs  gender   age  yearsmarried children  religiousness  education  \
0          0    male  37.0         10.00       no              3         18   
3          0    male  57.0         15.00      yes              5         18   
6          0  female  22.0          0.75       no              2         12   
9          0    male  22.0          1.50       no              4         14   
12         0    male  47.0         15.00      yes              5         17   
..       ...     ...   ...           ...      ...            ...        ...   
588        3  female  32.0         15.00      yes              4         16   
591       12    male  42.0         15.00      yes              3         18   
594        3    male  32.0         10.00      yes              4         14   
597        7  female  32.0         10.00      yes              2         18   
600        1  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
3             6       5  
6             1       3  
9             4       5  
12            6       4  
..          ...     ...  
588           4       4  
591           6       2  
594           4       3  
597           5       4  
600           1       5  

[201 rows x 9 columns]

## renaming (columns)

In [81]:
affairs_df.columns

Index(['affairs', 'gender', 'age', 'yearsmarried', 'children', 'religiousness',
       'education', 'occupation', 'rating'],
      dtype='object')

In [84]:
affairs_df.columns = ['affairs', 'gender', 'age', 'yearsmarried', 'has_children', 'religiousness',
       'education', 'occupation', 'rating']

In [85]:
affairs_df

affairs  gender   age  yearsmarried has_children  religiousness  \
0          0    male  37.0         10.00           no              3   
1          0  female  27.0          4.00           no              4   
2          0  female  32.0         15.00          yes              1   
3          0    male  57.0         15.00          yes              5   
4          0    male  22.0          0.75           no              2   
..       ...     ...   ...           ...          ...            ...   
596        1    male  22.0          1.50          yes              1   
597        7  female  32.0         10.00          yes              2   
598        2    male  32.0         10.00          yes              2   
599        2    male  22.0          7.00          yes              3   
600        1  female  32.0         15.00          yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 9 columns]

In [86]:
new_names = dict(gender = 'sex',
                 affairs = 'n_affairs',
                 rating = 'happy')

In [87]:
new_names['gender']

'sex'

In [88]:
affairs_df.rename(columns = new_names)

n_affairs     sex   age  yearsmarried has_children  religiousness  \
0            0    male  37.0         10.00           no              3   
1            0  female  27.0          4.00           no              4   
2            0  female  32.0         15.00          yes              1   
3            0    male  57.0         15.00          yes              5   
4            0    male  22.0          0.75           no              2   
..         ...     ...   ...           ...          ...            ...   
596          1    male  22.0          1.50          yes              1   
597          7  female  32.0         10.00          yes              2   
598          2    male  32.0         10.00          yes              2   
599          2    male  22.0          7.00          yes              3   
600          1  female  32.0         15.00          yes              3   

     education  occupation  happy  
0           18           7      4  
1           14           6      4  
2           12           1      4  
3           18           6      5  
4           17           6      3  
..         ...         ...    ...  
596         12           2      5  
597         18           5      4  
598         17           6      5  
599         18           6      2  
600         14           1      5  

[601 rows x 9 columns]

In [93]:
affairs_df.rename(columns = {'gender':'sex'}, inplace=True)

In [94]:
affairs_df

affairs     sex   age  yearsmarried has_children  religiousness  \
0          0    male  37.0         10.00           no              3   
1          0  female  27.0          4.00           no              4   
2          0  female  32.0         15.00          yes              1   
3          0    male  57.0         15.00          yes              5   
4          0    male  22.0          0.75           no              2   
..       ...     ...   ...           ...          ...            ...   
596        1    male  22.0          1.50          yes              1   
597        7  female  32.0         10.00          yes              2   
598        2    male  32.0         10.00          yes              2   
599        2    male  22.0          7.00          yes              3   
600        1  female  32.0         15.00          yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 9 columns]

## sorting

In [97]:
affairs_df.sort_values(by = ['religiousness', 'affairs'], ascending=False)

affairs     sex   age  yearsmarried has_children  religiousness  \
463       12  female  42.0        15.000          yes              5   
555       12    male  37.0        15.000          yes              5   
453        7    male  37.0        15.000          yes              5   
504        7  female  52.0        15.000          yes              5   
551        7    male  57.0        15.000          yes              5   
..       ...     ...   ...           ...          ...            ...   
368        0  female  32.0        10.000          yes              1   
380        0  female  27.0         4.000          yes              1   
396        0  female  22.0         1.500           no              1   
397        0  female  22.0         0.750           no              1   
426        0    male  22.0         0.125           no              1   

     education  occupation  rating  
463          9           4       1  
555         17           5       2  
453         18           6       2  
504         16           1       3  
551         20           4       5  
..         ...         ...     ...  
368         18           1       4  
380         16           5       5  
396         16           6       5  
397         14           4       5  
426         16           3       5  

[601 rows x 9 columns]

In [99]:
affairs_df.sort_index()

affairs     sex   age  yearsmarried has_children  religiousness  \
0          0    male  37.0         10.00           no              3   
1          0  female  27.0          4.00           no              4   
2          0  female  32.0         15.00          yes              1   
3          0    male  57.0         15.00          yes              5   
4          0    male  22.0          0.75           no              2   
..       ...     ...   ...           ...          ...            ...   
596        1    male  22.0          1.50          yes              1   
597        7  female  32.0         10.00          yes              2   
598        2    male  32.0         10.00          yes              2   
599        2    male  22.0          7.00          yes              3   
600        1  female  32.0         15.00          yes              3   

     education  occupation  rating  
0           18           7       4  
1           14           6       4  
2           12           1       4  
3           18           6       5  
4           17           6       3  
..         ...         ...     ...  
596         12           2       5  
597         18           5       4  
598         17           6       5  
599         18           6       2  
600         14           1       5  

[601 rows x 9 columns]