In [3]:
import rpy2
import pandas as pd

In [ ]:
from rpy2 import robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri

pandas2ri.activate()
R = ro.r
base = importr('base')

In [13]:
lme4 = importr('lme4')

In [9]:
weight_df = pd.read_csv('weight.csv')

m = R.lm('weight ~ height', data = weight_df)

print(base.summary(m))


Call:
(function (formula, data, subset, weights, na.action, method = "qr", 
    model = TRUE, x = FALSE, y = FALSE, qr = TRUE, singular.ok = TRUE, 
    contrasts = NULL, offset, ...) 
{
    ret.x <- x
    ret.y <- y
    cl <- match.call()
    mf <- match.call(expand.dots = FALSE)
    m <- match(c("formula", "data", "subset", "weights", "na.action", 
        "offset"), names(mf), 0L)
    mf <- mf[c(1L, m)]
    mf$drop.unused.levels <- TRUE
    mf[[1L]] <- quote(stats::model.frame)
    mf <- eval(mf, parent.frame())
    if (method == "model.frame") 
        return(mf)
    else if (method != "qr") 
        warning(gettextf("method = '%s' is not supported. Using 'qr'", 
            method), domain = NA)
    mt <- attr(mf, "terms")
    y <- model.response(mf, "numeric")
    w <- as.vector(model.weights(mf))
    if (!is.null(w) && !is.numeric(w)) 
        stop("'weights' must be a numeric vector")
    offset <- model.offset(mf)
    mlm <- is.matrix(y)
    ny <- if (mlm) 
        nrow(y)
   

In [10]:
R.coef(m)

array([-117.12802067,    1.14813765])

In [11]:
print(base.summary(m).rx2('coefficients'))

[[-1.17128021e+002  2.87869247e+000 -4.06879241e+001  3.07012392e-320]
 [ 1.14813765e+000  1.67681005e-002  6.84715391e+001  0.00000000e+000]]


In [12]:
# M <- lm(weight ~ height, data = weight_df)
# coef(M)
# summary(M)$coefficients
# plot(M)

In [19]:
sleepstudy_df = pd.read_csv('sleepstudy.csv')

In [18]:
cp ../data/sleepstudy.csv ./

In [21]:
sleepstudy_df

Reaction  Days Subject
0    249.5600     0    s308
1    258.7047     1    s308
2    250.8006     2    s308
3    321.4398     3    s308
4    356.8519     4    s308
..        ...   ...     ...
175  329.6076     5    s372
176  334.4818     6    s372
177  343.2199     7    s372
178  369.1417     8    s372
179  364.1236     9    s372

[180 rows x 3 columns]

In [23]:
m = lme4.lmer('Reaction ~ Days + (Days|Subject)', data = sleepstudy_df)

In [28]:
s = base.summary(m).rx2('coefficients')

In [27]:
type(s)

NoneType

In [30]:
type(s)

numpy.ndarray

In [31]:
R.predict(m)

array([253.6636558 , 273.32991752, 292.99617925, 312.66244097,
       332.3287027 , 351.99496442, 371.66122615, 391.32748787,
       410.9937496 , 430.66001132, 211.00636677, 212.85397211,
       214.70157746, 216.5491828 , 218.39678815, 220.24439349,
       222.09199884, 223.93960418, 225.78720952, 227.63481487,
       212.44469589, 217.46312538, 222.48155487, 227.49998436,
       232.51841385, 237.53684334, 242.55527283, 247.57370232,
       252.59213181, 257.6105613 , 275.09572441, 280.74866005,
       286.40159569, 292.05453133, 297.70746697, 303.36040261,
       309.01333825, 314.66627389, 320.31920952, 325.97214516,
       273.66541744, 281.06279178, 288.46016613, 295.85754048,
       303.25491483, 310.65228918, 318.04966353, 325.44703787,
       332.84441222, 340.24178657, 260.44467275, 270.63978171,
       280.83489067, 291.02999964, 301.2251086 , 311.42021757,
       321.61532653, 331.8104355 , 342.00554446, 352.20065343,
       268.24561346, 278.48926334, 288.73291322, 298.97